# Generated by Django 5.2.4 on 2025-08-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_options_order_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sgst_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cgst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_gst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_sgst',
        ),
    ]
