# Generated by Django 4.2.8 on 2026-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_options_order_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="initial_stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Stock quantity at time of creation"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("grams", "Grams"),
                    ("liter", "Liter"),
                    ("ml", "Milliliter"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
