# Generated by Django 4.2.8 on 2026-04-05 19:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_unit_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_value",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1"),
                help_text='Pack / unit size (e.g. 1 with kg → "1 kg", 500 with grams → "500 grams")',
                max_digits=12,
            ),
        ),
    ]
