# Generated by Django 4.2.8 on 2026-04-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_purchase_fields_cart_transaction_order_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company_gstin",
            field=models.CharField(
                blank=True,
                help_text="Supplier GSTIN (optional, 15 characters)",
                max_length=15,
            ),
        ),
    ]
