# Generated by Django 4.2.8 on 2026-04-07 04:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_company_gstin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount (unit_amount * quantity)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price per unit (AD Section)",
                max_digits=12,
            ),
        ),
    ]
