# Generated by Django 5.2.1 on 2026-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_net_amount_product_unit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesreport",
            name="sale_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
