# Generated by Django 5.2.1 on 2026-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_order_is_deleted_alter_order_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salesreport",
            name="sale_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
