# Generated by Django 5.2.1 on 2026-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_order_order_date_alter_salesreport_sale_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_invoice_number", models.CharField(max_length=100)),
                ("returned_invoice_number", models.CharField(max_length=100)),
                ("stock_returned", models.PositiveIntegerField()),
                ("current_stock", models.PositiveIntegerField()),
                ("return_date", models.DateField()),
                (
                    "taxable_unit_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("gst", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "taxable_total_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="store.product",
                    ),
                ),
                (
                    "store_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
