# Generated by Django 5.2.1 on 2026-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_productreturn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreturn",
            name="store_owner",
        ),
        migrations.AlterField(
            model_name="productreturn",
            name="taxable_total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productreturn",
            name="taxable_unit_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productreturn",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
