# Generated by Django 5.2.1 on 2026-04-12 08:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_productreturn_store_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="GST-inclusive total (net_amount + GST)",
                max_digits=12,
            ),
        ),
    ]
