# Generated by Django 5.2.1 on 2026-04-12 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="taxable_total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total taxable amount (taxable_unit_amount * quantity)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="taxable_unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price per unit (excl. GST)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_capacity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Quantity per unit (e.g. 50 for 50kg bag)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="GST-inclusive total",
                max_digits=12,
            ),
        ),
    ]
