# Generated by Django 5.2.1 on 2026-04-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_product_taxable_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
    ]
