# Generated by Django 5.2.1 on 2026-04-13 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_product_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_igst",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="igst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="igst",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="IGST percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="productreturn",
            name="igst",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
