# Generated by Django 4.2.7 on 2026-10-06 08:52
# Pre-existing drift: models.py already uses default=timezone.now (migration 0012 still said
# auto_now_add). This only syncs Django's migration state; no data is changed.

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_unique_together_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
