# Generated by Django 4.2.7 on 2026-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_repair_missing_financial_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store_owner', 'purchase_date'], name='store_prod_owner_pdate_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['return_date'], name='store_return_date_idx'),
        ),
    ]
