# Generated by Django 4.2.7 on 2026-10-06 08:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.CharField(choices=[('credited', 'Credited'), ('debited', 'Debited'), ('transferred', 'Transferred')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; the transaction type decides the direction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Reason / details, e.g. "Fertilizer supplier payment"')),
                ('transfer_direction', models.CharField(blank=True, choices=[('out', 'Out - to another account'), ('in', 'In - from another account')], default='', help_text='Only for Transferred: did the money leave this account or come into it?', max_length=3)),
                ('counterparty_account', models.CharField(blank=True, default='', help_text='Only for Transferred: the other account, e.g. "SBI Savings ****1234" or "Cash in hand"', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['store_owner', 'transaction_date'], name='bank_banktr_store_o_f54d8a_idx')],
            },
        ),
    ]
