# Generated by Django 5.2.4 on 2025-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_address',
            field=models.TextField(blank=True, help_text='Complete company address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number (Optional)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
