# Generated by Django 5.2.1 on 2025-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='plan',
            field=models.CharField(default='300-days', max_length=20),
        ),
    ]
